#!/bin/bash

# Determine the directory of the current script
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" &> /dev/null && pwd)"

# Detect the current shell
current_shell=$(basename "$SHELL")

case $current_shell in
    fish)
        "$SCRIPT_DIR/codecam.fish" "$@"
        ;;
    zsh|bash|sh)
        "$SCRIPT_DIR/codecam.sh" "$@"
        ;;
    *)
        echo "Unsupported shell: $current_shell"
        exit 1
        ;;
esac