name: CI

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11', '3.12']
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install package + dev deps
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install pytest ruff mypy build twine pip-audit

      - name: Lint (ruff)
        run: ruff check .

      - name: Type-check (mypy)
        run: mypy codecam

      - name: Unit tests
        run: pytest -q

      - name: Build sdist/wheel
        run: python -m build

      - name: Check package metadata
        run: python -m twine check dist/*

      - name: Dependency vulnerability audit
        run: pip-audit || true  # non-blocking for now
